name: Rename, Add, and Merge Markdown Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITBOOKKEY }}
        fetch-depth: 0

    - name: Set UTF-8 Encoding
      run: |
        export LC_CTYPE="UTF-8"
       
    - name: Rename and Copy Markdown files to koreanPageTitle, Rename Folders Based on README H1
      run: |
        for file in $(find developLog -type f -name '*.md'); do    

          # Markdown 파일 복사 및 이름 변경
          if [[ "$file" == *"README.md" ]] || [[ "$file" == *"SUMMARY.md" ]]; then
                echo "Skipping $file"
                continue
          fi
        
          title=$(grep -m 1 '^#' "$file" | sed 's/^# //')
          
          if [ -n "$title" ]; then
            dir=$(dirname "$file" | sed 's|developLog/||') # developLog 부분을 제거한 경로
            new_dir="temp_dir/$dir"
            new_filename="$new_dir/$title.md"
            
            mkdir -p "$new_dir"
            
            if [ -f "$new_filename" ]; then
              if cmp -s "$file" "$new_filename"; then
                echo "File $new_filename already exists and is identical. Skipping..."
              else
                echo "File $new_filename already exists but is different. Overwriting with new file."
                cp "$file" "$new_filename"
              fi
            else
              echo "Copying $file to $new_filename"
              cp "$file" "$new_filename"
            fi
          else
            echo "No valid title found in $file, skipping."
          fi
        done

        # .gitbook/assets 디렉토리 복사
        if [ -d "developLog/.gitbook/assets" ]; then
          mkdir -p "koreanPageTitle/.gitbook/assets"
          cp -r developLog/.gitbook/assets/* koreanPageTitle/.gitbook/assets/
          echo ".gitbook/assets directory copied to koreanPageTitle"
        fi

        # Copy SUMMARY.md
        if [ -f "developLog/SUMMARY.md" ]; then
          cp "developLog/SUMMARY.md" "temp_dir/SUMMARY.md"
          echo "SUMMARY.md copied to temp_dir"
        fi

    - name: Commit changes in koreanPageTitle
      run: |
        cd temp_dir
        git init
        git add -A
        git config --global user.name 'GoldenPearls'
        git config --global user.email 'prettylee620.naver.com'
        git commit -m "Rename and update Markdown files based on h1 titles in koreanPageTitle"
        git push https://${{ secrets.GITBOOKKEY }}@github.com/GoldenPearls/gitbook_public.git master:koreanPageTitle --force

  merge-to-main:
    needs: process-markdown
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITBOOKKEY }}
        fetch-depth: 0

    - name: Merge koreanPageTitle into main
      run: |
        git config --global user.name 'GoldenPearls'
        git config --global user.email 'prettylee620.naver.com'
        git fetch origin
        git checkout main
        git pull origin main
        git merge origin/koreanPageTitle --allow-unrelated-histories
        git push origin main
