on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITBOOKKEY }}
        fetch-depth: 0

    - name: Set UTF-8 Encoding
      run: |
        export LC_CTYPE="UTF-8"

    - name: Create New Directory and Process Files
      run: |
        # developLog 디렉토리 내의 모든 Markdown 파일 처리
        for file in $(find developLog -type f -name '*.md'); do
          if [[ "$file" == *"README.md" ]] || [[ "$file" == *"SUMMARY.md" ]]; then
                echo "Skipping $file"
                continue
          fi
        
          title=$(grep -m 1 '^#' "$file" | sed 's/^# //')
          
          if [ -n "$title" ]; then
            # 기존 파일 경로를 기반으로 새로운 파일 경로 생성
            new_dir="koreanPageTitle/$(dirname "$file")"
            new_filename="$new_dir/$title.md"
            
            # 새 디렉토리를 유지하며 파일 복사
            mkdir -p "$new_dir"
            echo "Copying $file to $new_filename"
            cp "$file" "$new_filename"
          else
            echo "No valid title found in $file, skipping."
          fi
        done

    - name: Commit changes
      run: |
        git add -A
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Copy and rename Markdown files based on h1 titles"
        git push https://${{ secrets.GITBOOKKEY }}@github.com/GoldenPearls/gitBook.git
