name: Rename and Commit Markdown Files

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로우 트리거
  workflow_dispatch:  # 수동으로 워크플로우를 실행할 수 있는 옵션

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
          token: ${{ secrets.GITBOOKKEY }}
          fetch-depth: 0
          ref: main

    - name: Set UTF-8 Encoding
      run: |
        export LC_CTYPE="UTF-8"  # UTF-8 인코딩을 명시적으로 설정

    - name: Rename Markdown files
      run: |
        for file in developLog/*.md; do
        # 첫 번째 H1 제목을 추출하여 제목으로 사용
        title=$(grep -m 1 '^# ' "$file" | sed 's/^# //')
        
        if [ -n "$title" ]; then
          # 새 파일명을 제목을 기반으로 생성
          new_filename="developLog/$title.md"
          
          # 파일 이름이 동일한 경우에는 mv 명령을 건너뜁니다
          if [ "$file" != "$new_filename" ]; then
            mv "$file" "$new_filename"
          fi
        fi
        done

    - name: Commit changes
      run: |
        git add .
         git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Rename Markdown files based on h1 titles"
        git push https://${{ secrets.GITBOOKKEY }}@github.com/GoldenPearls/gitBook.git  # 변경사항을 main 브랜치로 푸시
